name: Run PR Checks

on:
  push:

jobs:
  prcheck:
    runs-on: ubuntu-latest
    env:
      HYPOTHESIS_PROFILE: ci
      CHALICE_TEST_EXTENDED_PACKAGING: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Set up Python 3.13
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          make install-dev-deps
      - name: Run PRCheck
        run: make prcheck
  merge-checks-complete:
        runs-on: ubuntu-latest
        needs: [prcheck]
        steps:
          - name: merge-checks-complete
            run: echo 0
